spring:
  application:
    name: member_server
  config:
    import: "optional:configserver:http://team5-config-server:8888/"
  cloud:
    config:
      discovery:
        enabled: false

eureka:
  client:
    service-url:
      # 초기 기동 시 유레카 위치를 알려줌
      defaultZone: http://team5-eureka-server:10481/eureka/